services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=development20
    ports:
      - "1433:1433"
    volumes:
      - ./scripts:/scripts:ro
    entrypoint: >
      bash -c "
        /opt/mssql/bin/sqlservr & pid=\$!; \
        until /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P development20 -Q 'SELECT 1' &>/dev/null; do sleep 2; done; \
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P development20 -i /scripts/create-sqlserver-user.sql; \
        wait \$pid
      "

  adminer:
    build:
      context: ./adminer
    container_name: adminer
    environment:
      - TDSVER=7.4
    depends_on:
      - mssql
    ports:
      - "8081:8080"
