services:
  mssql-express:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-express
    environment:
      ACCEPT_EULA: "Y"              # Aceptas la licencia
      SA_PASSWORD: "Dev20Pass!"     # Debe cumplir la política: 8+ caracteres, mayúsculas, minúsculas, dígitos, símbolos
      MSSQL_PID: "Express"          # Indica SQL Server Express Edition :contentReference[oaicite:0]{index=0}
    ports:
      - "1433:1433"                 # Expone al host en todas las interfaces
    volumes:
      - mssql_data:/var/opt/mssql   # Persistencia de datos

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"                 # http://localhost:8081
    depends_on:
      mssql-express:
        condition: service_started

volumes:
  mssql_data:
